# Generated by Django 3.2.10 on 2022-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='article',
            name='about',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
