# Generated by Django 3.2.10 on 2022-01-08 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModel', '0002_auto_20220107_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
