# Generated by Django 3.2.10 on 2022-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModel', '0003_article_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='img_src',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='watch_num',
            field=models.IntegerField(default=0),
        ),
    ]
