# Generated by Django 3.2.10 on 2022-01-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModel', '0004_auto_20220108_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_src',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
