# Generated by Django 3.2.10 on 2022-01-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModel', '0005_auto_20220108_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.FileField(upload_to='uploads/markdown'),
        ),
    ]
