# Generated by Django 3.2.10 on 2022-01-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArticleModel', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='Empty'),
        ),
    ]
