# Generated by Django 3.2.10 on 2022-01-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='请填入HTML格式文字')),
            ],
        ),
        migrations.CreateModel(
            name='FriendUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageSrc', models.TextField(default='https://inews.gtimg.com/newsapp_ls/0/14401632748/0.jpg')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=50)),
                ('content', models.TextField(default='www.baidu.com')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.IntegerField(default=0)),
                ('content', models.TextField(default='请添加文字')),
            ],
        ),
    ]
