# Generated by Django 3.2.10 on 2022-01-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteConfig', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='imageSrc',
            field=models.TextField(default='https://inews.gtimg.com/newsapp_ls/0/14401632748/0.jpg'),
        ),
    ]
