# Generated by Django 3.2.10 on 2022-01-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteConfig', '0003_contact_imagesrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.AddField(
            model_name='contact',
            name='linkSrc',
            field=models.TextField(default='https://www.jinlog.com'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
