# Generated by Django 3.2.10 on 2022-01-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteConfig', '0004_auto_20220109_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendurl',
            old_name='content',
            new_name='url',
        ),
    ]
